package processos.recebidos;

import processos.criarpedido.*;
import entidades.Pedido;
import gui.DialogPadrao;
import java.awt.Window;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ListSelectionModel;

public class FormRecebidos extends DialogPadrao {
    
    private List<Pedido> listagem;
    
    public FormRecebidos(Window parent) {
        super(parent, ModalityType.MODELESS);
        initComponents();
        
        tablePadrao1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
        comboBoxVendedor1.atualizaComboComOpcaoTodos();
        
        atualizaListagem();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePadrao1 = new gui.TablePadrao();
        comboBoxVendedor1 = new gui.ComboBoxVendedor();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Consulta");

        tablePadrao1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Vendedor", "Aluno", "Curso", "Nº de Registro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePadrao1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(tablePadrao1);
        if (tablePadrao1.getColumnModel().getColumnCount() > 0) {
            tablePadrao1.getColumnModel().getColumn(0).setPreferredWidth(75);
            tablePadrao1.getColumnModel().getColumn(1).setPreferredWidth(100);
            tablePadrao1.getColumnModel().getColumn(2).setPreferredWidth(350);
            tablePadrao1.getColumnModel().getColumn(3).setPreferredWidth(350);
            tablePadrao1.getColumnModel().getColumn(4).setPreferredWidth(75);
        }

        comboBoxVendedor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxVendedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVendedor1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Vendedor:");

        jButton1.setText("Receber");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxArea1ActionPerformed
        atualizaListagem();
    }//GEN-LAST:event_comboBoxArea1ActionPerformed

    private void comboBoxVendedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVendedor1ActionPerformed
        atualizaListagem();
    }//GEN-LAST:event_comboBoxVendedor1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new PedidoController().receberCurso(getPedidoSelecionado());
        atualizaListagem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private Map getParametros() {
        Map<String, Object> list = new HashMap<>();
        list.put("codigo_vendedor", comboBoxVendedor1.getVendedorSelecionado().getCodigo());
        list.put("nome_vendedor", comboBoxVendedor1.getVendedorSelecionado().getNome());
        return list;
    }
    
    
    private void atualizaListagem() {
        tablePadrao1.limparTabela();
        listagem = new PedidoController().listagemRecebimentoPendente(comboBoxVendedor1.getVendedorSelecionado());
        if(listagem != null) {
            for(Pedido p : listagem) {
                if(p.isCancelado()) {
                    tablePadrao1.adicionarLinha(new Object[] {getTextRiscado(p.getDataCadastroToString()), getTextRiscado(p.getAluno().getNome()), getTextRiscado(p.getVendedor().getNome()), 
                        getTextRiscado(p.getCurso().getNome()), getTextRiscado(p.getDataInicioToString()), getTextRiscado(p.getDataTerminoToString()), getTextRiscado(p.getNumeroRegistroToString()),
                        getTextRiscado(p.getDataEmissaoCertificadoToString())});
                } else {
                    tablePadrao1.adicionarLinha(new Object[] {p.getDataCadastroToString(), p.getVendedor().getNome(), p.getAluno().getNome(),
                        p.getCurso().getNome(), p.getDataInicioToString(), p.getDataTerminoToString(), p.getNumeroRegistroToString(),
                        p.getDataEmissaoCertificadoToString()});
                }
            }
        }
        tablePadrao1.selectAndScroll(0);
    }
    
    private List<Pedido> getPedidosSelecionados() {
        List<Pedido> listagemPedidosSel = new ArrayList<>();
        for(int i : tablePadrao1.getSelectedRows()) {
            listagemPedidosSel.add(listagem.get(i));
        }
        return listagemPedidosSel;
    }
    
    private Pedido getPedidoSelecionado() {
        if(tablePadrao1.getSelectedRow() != -1) {
            return listagem.get(tablePadrao1.getSelectedRow());
        }
        return null;
    }
    
    private String getTextRiscado(String text) {
        return "<html><strike>" + text + "</html></strike>";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.ComboBoxVendedor comboBoxVendedor1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private gui.TablePadrao tablePadrao1;
    // End of variables declaration//GEN-END:variables
}
