/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFerramenta.java
 *
 * Created on 28/08/2012, 11:06:45
 */
package processos.montarpedido;

import configuracoes.ConfiguracoesController;
import entidades.Apostila;
import entidades.Configuracoes;
import processos.criarpedido.PedidoController;
import entidades.Pedido;
import entidades.PedidoItem;
import gui.DialogPadrao;
import java.io.File;
import java.io.IOException;
import java.util.List;
import mc.ConfiguracoesGerais;
import util.Cmd;
import util.CopiarArquivos;
import util.ExcluirArquivos;
import util.Msg;
import util.TrataException;

/**
 *
 * @author marcelo
 */
public class FormGravarCd extends DialogPadrao {

    private List<Pedido> listagemPedidos;
    
    /** Creates new form LoginFerramenta */
    public FormGravarCd(List<Pedido> listagemPedidos) {
        super(null, ModalityType.APPLICATION_MODAL);
        initComponents();
        this.listagemPedidos = listagemPedidos;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIniciarGravacao = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grava CD");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnIniciarGravacao.setText("Iniciar Gravação");
        btnIniciarGravacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarGravacaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarGravacao);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        jLabel1.setText("O que você deseja fazer?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnIniciarGravacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarGravacaoActionPerformed
    if(new File(ConfiguracoesGerais.NERO_CMD).exists()) {
        
        ExcluirArquivos.deleteDir(ConfiguracoesGerais.DIRETORIO_TEMP_GRAVACAO);
        
        try {
            
            for(Pedido p : listagemPedidos) {
                for(Apostila a : p.getCurso().getListagemApostilas()) {
                    new CopiarArquivos().copiarArquivoParaDiretorio(a.getCaminhoCompleto(), ConfiguracoesGerais.DIRETORIO_TEMP_GRAVACAO);
                }
            }
            
            new Cmd().executaSemAguardar(new ConfiguracoesController().carregar().getCaminhoAplicacao() + "GravarCd.bat");
            System.out.println(ConfiguracoesGerais.NERO_CMD + 
                    "--write --drivename E --real --speed 4 --iso Alpha --iso-mode2 "
                    + "--detect_non_empty_cdrw --enable_abort --underrun_prot "
                    + "--create_iso_fs " + ConfiguracoesGerais.DIRETORIO_TEMP_GRAVACAO + "*.* --force_erase_cdrw");
            
            this.dispose();
            
            
        } catch (IOException ex) {
            TrataException.fatal(ex);
        } catch (InterruptedException ex) {
            TrataException.fatal(ex);
        }
    } else {
        new Msg().msgAtencao("NeroCmd.exe não encontrado.");
    }
}//GEN-LAST:event_btnIniciarGravacaoActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciarGravacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
