package cadastro.cursos;

import entidades.Aluno;
import entidades.Curso;
import gui.DialogPadrao;
import java.awt.Window;
import java.util.List;

public class FormListagemCurso extends DialogPadrao {
    
    private List<Curso> listagem;
    
    public FormListagemCurso(Window parent) {
        super(parent, ModalityType.MODELESS);
        initComponents();
        
        atualizaListagem();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNovoAnalistaAutomacao = new javax.swing.JButton();
        btnNovoAPartirDeste = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePadrao1 = new gui.TablePadrao();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();

        setTitle("Listagem de Cursos");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnNovoAnalistaAutomacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoAnalistaAutomacao.setText("Novo");
        btnNovoAnalistaAutomacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAnalistaAutomacaoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovoAnalistaAutomacao);

        btnNovoAPartirDeste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovoAPartirDeste.setText("Novo a Partir Deste");
        btnNovoAPartirDeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAPartirDesteActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovoAPartirDeste);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        btnExcluirUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluirUsuario);

        tablePadrao1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Área", "Nome", "Carga Horária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePadrao1);
        if (tablePadrao1.getColumnModel().getColumnCount() > 0) {
            tablePadrao1.getColumnModel().getColumn(0).setPreferredWidth(25);
            tablePadrao1.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablePadrao1.getColumnModel().getColumn(2).setPreferredWidth(400);
            tablePadrao1.getColumnModel().getColumn(3).setPreferredWidth(75);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome do Curso:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 329, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        new CursoController().deletar(getCursoSelecionado());
        atualizaListagem();
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void btnNovoAnalistaAutomacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAnalistaAutomacaoActionPerformed
        new FormCadastroCurso().setVisible(true);
        atualizaListagem();
    }//GEN-LAST:event_btnNovoAnalistaAutomacaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FormCadastroCurso(getCursoSelecionado(), false).setVisible(true);
        atualizaListagem();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboBoxArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxArea1ActionPerformed
        atualizaListagem();
    }//GEN-LAST:event_comboBoxArea1ActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        atualizaListagem();
    }//GEN-LAST:event_txtNomeKeyReleased

    private void btnNovoAPartirDesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAPartirDesteActionPerformed
        new FormCadastroCurso(getCursoSelecionado(), true).setVisible(true);
        atualizaListagem();
    }//GEN-LAST:event_btnNovoAPartirDesteActionPerformed

    private void atualizaListagem() {
        tablePadrao1.limparTabela();
        listagem = new CursoController().listagem(txtNome.getText());
        if(listagem != null) {
            for(Curso c : listagem) {
                tablePadrao1.adicionarLinha(new Object[] {c.getCodigo(), c.getAreaToString(), c.getNome(), c.getTotalCargaHoraria()});
            }
        }
    }
    
    private Curso getCursoSelecionado() {
        if(tablePadrao1.getSelectedRow() != -1) {
            return listagem.get(tablePadrao1.getSelectedRow());
        }
        return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnNovoAPartirDeste;
    private javax.swing.JButton btnNovoAnalistaAutomacao;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private gui.TablePadrao tablePadrao1;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
